# Your Github username and API token
github:
  username: my_github_username
  token: my_github_api_token

# Optional CircleCI token
workflows:
  circleci:
    token: my_circleci_token

# The default pull request merge method. Can be:
#
# * "merge" to create a merge commit. This is the default.
# * "squash" to squash the pull request commits into a single one.
# * "rebase" to add all commits in the pull request into the target branch individually.
#
# Note that the repository may be configured to only allow a subset of these. This means
# we will try the default method but otherwise attempt the other 2 if the default one failed.
merge:
  default_method: squash


# The pull request reviews configuration. mergebro will fetch and honor the branch protection settings from the
# target branch. However, this is not available in repos you don't own so you can provide some default and
# per repo settings to make sure there's enough approvals before attempting to merge a change.
reviews:
  # By default require at least 1 approval on all pull requests
  approvals: 1

# Configurations to be applied to specific repos
repos:
  - repo: mfontanini/mergebro
    # Specify 2 required approvals for this one repo
    reviews:
      approvals: 2

    statuses:
      # Claim this particular status check in the PR is critical (and non flaky!) and therefore we bail out
      # if we see even a single failure on it
      - name: some critical, non flaky, CI step
        max_failures: 1

  - repo: rust-lang/*
    # Specify higher required approvals for any repo under rust-lang
    reviews:
      approvals: 3
